KulturniCentar/Controllers/KategorijaController.cs
using KulturniCentar.Data.Models;
using KulturniCentar.Helper;
using KulturniCentar.ViewModels;
using KulturniCentar.Web.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace KulturniCentar.Controllers
{
    public class KategorijaController : Controller
    {
        private readonly CoreDbContext _db;
        private readonly Authorize _authorize;

        public KategorijaController(CoreDbContext db)
        {
            _db = db;
            _authorize = new Authorize(db);
        }
        public IActionResult Index()
        {
            if (_authorize.IsAuthorized())
            {
                var model = new KategorijaIndexVM()
                {
                    rows = _db.Kategorija.Select(x => new KategorijaIndexVM.Row
                    {
                        Id = x.Id,
                        Naziv = x.Naziv,
                        Opis = x.Opis,
                        BrojKurseva = x.Kurs.Count()
                    }).ToList()
                };
                return View("Index", model);
            }
            return BadRequest("Niste autorizovani!");
        }

        public IActionResult Obrisi(int id)
        {
            if (_authorize.IsAuthorized() && _authorize.IsAdmin())
            {
                Kategorija k = _db.Kategorija.Find(id);
                _db.Kategorija.Remove(k);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return BadRequest("Niste autorizovani!");
        }

        public IActionResult Dodaj()
        {
            if (_authorize.IsAuthorized() && _authorize.IsAdmin())
            {
                var model = new Kategorija();
                return View("Dodaj", model);
            }
            return BadRequest("Niste autorizovani!");
        }
        public IActionResult Uredi(int Id)
        {
            if (_authorize.IsAuthorized() && _authorize.IsAdmin())
            {
                var model = _db.Kategorija.Find(Id);
                return View("Uredi", model);
            }
            return BadRequest("Niste autorizovani!");
        }
        public IActionResult Snimi(Kategorija x)
        {
            if (_authorize.IsAuthorized() && _authorize.IsAdmin())
            {
                Kategorija k;
                if (x.Id==0)
                {
                    k = new Kategorija();
                    _db.Kategorija.Add(k);
                }
                else
                {
                    k = _db.Kategorija.Find(x.Id);
                }
                k.Naziv = x.Naziv;
                k.Opis = x.Opis;
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return BadRequest("Niste autorizovani!");
        }
        public IActionResult Detalji(int id)
        {
            if (_authorize.IsAuthorized())
            {
                Kategorija x = _db.Kategorija.Where(k => k.Id == id)
                                         .Include(k => k.Kurs)
                                         .SingleOrDefault();

                var model = new KategorijaDetaljiVM()
                {
                    Id = x.Id,
                    Naziv = x.Naziv,
                    Opis = x.Opis,
                    BrojKurseva = x.Kurs.Count()
                };
                return View("Detalji", model);
            }
            return BadRequest("Niste autorizovani!");
        }
    }
}

KulturniCentar/Views/Kategorija/Detalji.cshtml
@using KulturniCentar.ViewModels
@using KulturniCentar.Data.Models

@model KategorijaDetaljiVM

@{
    ViewData["Title"] = "Detalji";
}

<div>
    <div class="form-group">
        <label> Naziv kategorije : @Model.Naziv </label>
        @*<input type="text" class="form-group" readonly value="@Model.Naziv" />*@
    </div>
    <div class="form-group">
        <label>Opis kategorije : @Model.Opis</label>
    </div>
    <div class="form-group">
        <label> Broj kurseva u kategoriji : </label>
        <input asp-for="@Model.BrojKurseva" readonly />
    </div>
</div>

<div id="nekiID" style="border: 1px black solid"></div>

<script>
    $(document).ready(function(parameters) {
        $.get("/stavkeajax/index?kategorijaId=@Model.Id",
            function(rezultat, status) {
                $("#nekiID").html(rezultat);

            });
    });
</script>

KulturniCentar/Views/Kategorija/Dodaj.cshtml
@using KulturniCentar.ViewModels
@using KulturniCentar.Data.Models

@model Kategorija

@{
    ViewData["Title"] = "Dodaj";
}

<h2>Dodaj kategoriju</h2>

<form asp-action="Snimi" asp-controller="Kategorija">
    <div>
        <label>Naziv kategorije:</label>
        <div>
            <input asp-for="@Model.Naziv" class="form-control" required /> 
        </div>
    </div>
    <div>
        <label> Opis kategorije:</label>
        <div>
            <input asp-for="@Model.Opis" class="form-control" required />
        </div>
    </div>

    <input type="submit" value="Snimi" />
</form>

KulturniCentar/Views/Kategorija/Index.cshtml
@using KulturniCentar.ViewModels
@using KulturniCentar.Data.Models

@model KategorijaIndexVM
@{
   ViewData["Title"] = "Kategorija";
}

<table class="table table-striped">
    <thead>
        <tr>
            <th> Naziv kategorije </th>
            <th> Opis </th>
            <th> Broj kurseva </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var x in Model.rows)
        {
        <tr>
            <td> @x.Naziv</td>
            <td> @x.Opis</td>
            <td> @x.BrojKurseva</td>
            <td>
                @if (Global.Role == "Admin")
                {
                    <a asp-action="Uredi" asp-route-id="@x.Id" class="btn btn-danger">Uredi</a>
                    <a asp-action="Obrisi" asp-route-id="@x.Id" class="btn btn-danger">Obrisi</a>
                }
                    <a asp-action="Detalji" asp-route-id="@x.Id" class="btn btn-info">Detalji</a>
                </td>
        </tr>
        }
    </tbody>
</table>
@if (Global.Role == "Admin")
{
    <a asp-action="Dodaj" class="btn btn-success">Dodaj</a>
}

KulturniCentar/Views/Kategorija/Uredi.cshtml
@model KulturniCentar.Data.Models.Kategorija

<form asp-action="Snimi">
    <input asp-for="Id" hidden />
    <div class="form-group">
        <label>Naziv :</label>
        <input asp-for="Naziv" class="form-control"  value="@Model.Naziv" required/>
    </div>
    <div class="form-group">
        <label>Opis:</label>
        <input asp-for="Opis" class="form-control"  value="@Model.Opis" required/>
    </div>
    <input type="submit" class="btn btn-info" value="Snimi" />
</form>