KulturniCentar/Controllers/KursController.cs
using KulturniCentar.Data.Models;
using KulturniCentar.Helper;
using KulturniCentar.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace KulturniCentar.Controllers
{
    public class KursController : Controller
    {
        private readonly CoreDbContext _db;
        private readonly Authorize _authorize;

        public KursController(CoreDbContext db)
        {
            _db = db;

            _authorize = new Authorize(db);
        }
        public IActionResult Index()
        {
            if (_authorize.IsAuthorized())
            {
                var model = new KursIndexVM()
                {
                    rows = _db.Kurs.Select(x => new KursIndexVM.Row
                    {
                        Naziv = x.Naziv,
                        MaxBrojPolaznika = x.MaxBrojPolaznika,
                        Kategorija = x.Kategorija.Naziv,
                        Predavac = x.Predavac.Ime,
                        KursId = x.Id
                    }).ToList()
                };
                return View("Index", model);
            }
            return BadRequest("Niste autorizovani!");
        }

        public IActionResult Dodaj()
        {

            if (_authorize.IsAuthorized() && _authorize.IsAdmin())
            {
                var ulazniModel = new KursDodajUrediVM();
                ulazniModel.KursId = 0;
                ulazniModel.Predavaci = _db.Predavac
                    .Select(x => new SelectListItem
                    {
                        Value = x.Id.ToString(),
                        Text = x.Ime
                    }).ToList();

                ulazniModel.Kategorije = _db.Kategorija
                     .Select(x => new SelectListItem
                     {
                         Value = x.Id.ToString(),
                         Text = x.Naziv
                     }).ToList();
                return View("DodajUredi", ulazniModel);
            }
            return BadRequest("Niste autorizovani!");
        }

        public IActionResult Snimi(int kursId,int KategorijaId,string naziv,int maxBrojPolaznika,int PredavacId,int MaterijalId)
        {
            if (_authorize.IsAuthorized() && _authorize.IsAdmin())
            {
                Kurs x;
                if (kursId == 0)
                {
                    x = new Kurs();
                    _db.Kurs.Add(x);
                }
                else
                {
                    x = _db.Kurs.Find(kursId);
                }
                x.Id = kursId;
                x.Naziv = naziv;
                x.MaxBrojPolaznika = maxBrojPolaznika;
                x.KategorijaId = KategorijaId;
                x.PredavacId = PredavacId;
                //x.MaterijaliId = MaterijalId;

                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return BadRequest("Niste autorizovani!");
        }

        public IActionResult Obrisi(int kursId)
        {
            if (_authorize.IsAuthorized() && _authorize.IsAdmin())
            {
                Kurs k = _db.Kurs.Find(kursId);
                _db.Kurs.Remove(k);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return BadRequest("Niste autorizovani!");
        }

        public IActionResult Uredi(int kursId)
        {
            if (_authorize.IsAuthorized() && _authorize.IsAdmin())
            {
                Kurs k = _db.Kurs.Find(kursId);

                //trebat ce biti implementirano preko VM-a kursDetalji/kursEdit, ali treba i povuci selectovanu
                //vrijednost liste, trenutno implentirano kao readonly detalji
                KursDodajUrediVM model = new KursDodajUrediVM
                {
                    KursId = kursId,
                    Naziv = k.Naziv,
                    MaxBrojPolaznika = k.MaxBrojPolaznika,
                    Predavaci = _db.Predavac.Select(w => new SelectListItem
                    {
                        Value = w.Id.ToString(),
                        Text = w.Ime + " " + w.Prezime
                    }).ToList(),
                    Kategorije = _db.Kategorija.Select(k => new SelectListItem
                    {
                        Value = k.Id.ToString(),
                        Text = k.Naziv
                    }).ToList(),
                    Materijali = _db.Materijali.Select(m => new SelectListItem
                    {
                        Value = m.Id.ToString(),
                        Text = m.Naziv
                    }).ToList()
                };
                return View("DodajUredi", model);
            }
            return BadRequest("Niste autorizovani!");
        }
    }
}

KulturniCentar/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Kulturni centar KC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />

    <script src="/lib/jquery/dist/jquery.js"></script>
    <script src="/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="/js/site.js"></script>

    <script src="/jsFIT.js"></script>
</head>
<body>
    <header>
        @if (Global.Token != null)
        {
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Kulturni centar</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Kurs" asp-action="Index">Kurs</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Kategorija" asp-action="Index">Kategorija</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Predavac" asp-action="Index">Predavac</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Polaznik" asp-action="Index">Polaznik</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Notifikacija" asp-action="Index">Notifikacija</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Ciklus" asp-action="Index">Ciklus</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Zahtjev" asp-action="Index">Zahtjev</a>
                        </li>
                        @if (Global.Role == "Polaznik")
                            {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Polaznik" asp-action="MojiPodaci">Moji Podaci</a>
                        </li>
                            }
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="LogOut">LogOut</a>
                        </li>
                    </ul>
                </div>

            </div>
        </nav>
        }
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Test - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    <script src="/jsFIT.js"></script>

</body>
</html>